[0m09:17:52.446522 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f83f984f3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f83fa635be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f83fa635d90>]}


============================== 09:17:52.451160 | fe82ed06-2d8d-4c40-9b22-f04a71a3afea ==============================
[0m09:17:52.451160 [info ] [MainThread]: Running with dbt=1.9.3
[0m09:17:52.451670 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ajitpani/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init dbt_workspace', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:17:52.461423 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/Users/ajitpani/.dbt')}
[0m09:17:52.461720 [info ] [MainThread]: Creating dbt configuration folder at 
[0m09:17:52.463033 [debug] [MainThread]: Starter project path: /Users/ajitpani/Documents/Snowflake_python_code/github/neonblue_project/dbt_workspace/dbt-env/lib/python3.9/site-packages/dbt/include/starter_project
[0m09:17:52.466411 [info ] [MainThread]: 
Your new dbt project "dbt_workspace" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:17:52.466690 [info ] [MainThread]: Setting up your profile.
[0m09:17:52.467202 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m09:17:52.470656 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.09437167, "process_in_blocks": "0", "process_kernel_time": 0.123011, "process_mem_max_rss": "360693760", "process_out_blocks": "0", "process_user_time": 0.997111}
[0m09:17:52.471437 [debug] [MainThread]: Command `dbt init` failed at 09:17:52.471061 after 0.10 seconds
[0m09:17:52.471800 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f83f984f3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f83f8f383d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f83f8f266d0>]}
[0m09:17:52.472127 [debug] [MainThread]: Flushing usage events
[0m09:17:53.019002 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:19:21.493530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febf96d0f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fec085f4400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fec085f4220>]}


============================== 09:19:21.501884 | c992046e-c39b-400f-b5fa-f42b5c2dc470 ==============================
[0m09:19:21.501884 [info ] [MainThread]: Running with dbt=1.9.3
[0m09:19:21.502611 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ajitpani/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_workspace', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:19:21.545279 [info ] [MainThread]: A project called dbt_workspace already exists here.
[0m09:19:21.551852 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.14860584, "process_in_blocks": "0", "process_kernel_time": 0.155603, "process_mem_max_rss": "365527040", "process_out_blocks": "0", "process_user_time": 1.113069}
[0m09:19:21.552576 [debug] [MainThread]: Command `dbt init` succeeded at 09:19:21.552210 after 0.15 seconds
[0m09:19:21.552939 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febf96d0f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7febfa4b8280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fec085dd280>]}
[0m09:19:21.553249 [debug] [MainThread]: Flushing usage events
[0m09:19:22.043224 [debug] [MainThread]: An error was encountered while trying to flush usage events
